In [2]:
%%capture
!pip install duckdb

In [3]:
import duckdb

conn = duckdb.connect('kcc_queries_processed.duckdb')

conn.execute("SHOW TABLES").fetch_df()

             name
0    dim_category
1  dim_demography
2      dim_sector
3     fct_queries

In [ ]:
conn.execute("SELECT * FROM fct_queries ORDER BY created_on DESC LIMIT 5").fetch_df()

,query_id,created_on,state_id,category_id,sector_id,crop,query_type,query_text,kcc_ans
0,Nm9WGVtoLj2tCg,2025-04-30 22:01:18.353,36,5,1,Wheat,Post Harvest Preservation,Farmer asked query on Weather,"महोदय, मौसम के पूर्वानुमान के अनुसार आपके क्षे..."
1,Nm9WGVtoLj2tCg,2025-04-30 22:01:18.353,36,5,1,Wheat,Post Harvest Preservation,Farmer asked query on Weather,"महोदय, मौसम के पूर्वानुमान के अनुसार आपके क्षे..."
2,16nP5uw0fF/Hsw,2025-04-30 21:59:24.733,15,11,4,Apple,Plant Protection,Farmer asked query on Weather,मौसम पूर्वानुमान जिला मंडी और विकास खंड करसोग ...
3,16nP5uw0fF/Hsw,2025-04-30 21:59:24.733,15,11,4,Apple,Plant Protection,Farmer asked query on Weather,मौसम पूर्वानुमान जिला मंडी और विकास खंड करसोग ...
4,dYt7EPHyzz9HdQ,2025-04-30 21:58:10.180,38,19,1,Others,Government Schemes,ASKING ABOUT GOVERNMENT SCHEME OF PM-KISAN .,FTO processed :- No\nPayment Status :\nRft Si...

Bad pipe message: %s [b'0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7\r\nHost: localhost:39179\r\nUs', b'-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.']
Bad pipe message: %s [b'0.0 Safari/537.36\r\nAccept-Encoding: gzip, defla']
Bad pipe message: %s [b', br, zstd\r\nAccept-Language: en-US,en;q=0.9,en-GB;q=0.8,en-IN;q=0.7,de;q=0.6\r\nCache-Control: max-age=0\r\nReferer: ht', b's://github.com/\r\nX-Request-ID: 2a22044c633cc432f609a292b09026b0\r\nX-Real-IP: 92.72.33.64\r\nX-Forwarded-Port: 443\r\nX-F']
Bad pipe message: %s [b'warded-Scheme: https\r\nX-Original-URI: /\r\nX-Scheme: https\r\nsec-fetch-site: cross-site\r\nsec-fetch-mode: navigate']
Bad pipe message: %s [b'sec-fetch-de']
Bad pipe message: %s [b': document\r\nsec-ch-ua: "Google Chrome";v="137", "Chromium";v="137", "Not/A)Brand";v="24"\r\nsec-ch-ua-mobile: ?0\r\nse']
Bad pipe message: %s [b'ch-ua-platform: "Windows"\r\npriority: u=0, i\r\nX-Original-Proto: https\r\nX-Forwarded-Proto: https\r\nX-', b'rwarded-Host: crispy-bassoon-p6vwxgwgg54c6xx6-39179.app.github.dev\r\nX', b'orwarded-For: 92.72.33.64\r\nProxy-Connection:']